.STRINGS
$ca.err[1]  ""
$ca.err[2]  ""
$ca.err[3]  ""
$ca.err[4]  ""
$ca.reg.mod[1] "a.scobra.cal"
$cf.clr     "^{[H^{[J"
$cf.dev     "DISK>"
$cf.dir     "\CONFIG_C\"
$cf.file    "ADEPTSYS.CFG"
$cf.key     "ENTER"
$cmd_str[1,1] "70"
$cmd_str[1,2] "15"
$cmd_str[2,1] "70"
$cmd_str[2,2] "15"
$cmd_str2   "15"
$come_str[1,1] ""
$come_str[1,2] "cmd15,397.89,405.95,0.18,435.53,-85.61,318.70,1^j^m"
$come_str[2,1] ""
$come_str[2,2] ""
$come_str[1] "cmd70,0,0^^^^^^^^j^^^^^^^^m"
$come_str[2] "^^^^^^^^`"
$err_code   "1"
$err_code[1] "1"
$err_code[2] "1"
$err_message[1] " -406"
$err_message[2] " -406"
$fw.gtype[0] "Empty"
$fw.gtype[1] "Node information"
$fw.gtype[2] "Axis"
$fw.gtype[3] "Digital input"
$fw.gtype[4] "Digital output"
$fw.gtype[5] "Serial I/O"
$fw.gtype[6] "Fast digital input"
$fw.gtype[7] "Multi-axis robot"
$fw.module  "SMARTLNK"
$fw.version "16.4A2"
$opt.d[1]   "V+ Version 11"
$opt.d[2]   "V+ Extensions"
$opt.d[3]   "OEM Option"
$opt.d[4]   "Kinematic Modules"
$opt.d[5]   "Integrated Motion and Vision"
$opt.d[6]   "Vision"
$opt.d[7]   "Enhanced Kinematic Modules"
$opt.d[8]   "AIM Versions 2.3 and 3.0"
$opt.d[9]   "AIM Extensions"
$opt.d[10]  "Adept Robot"
$opt.d[11]  "GEM and SECS-I/II Applications"
$opt.d[12]  "AIM Applications"
$opt.d[13]  "Enhanced Trajectory Control"
$opt.d[14]  "AdeptTCP/IP Protocol Access"
$opt.d[15]  "AdeptNFS Client"
$opt.d[16]  "AdeptFTP Client/Server"
$opt.d[17]  "Two Adept Robots"
$opt.d[18]  "Third-Party Board Support"
$opt.d[19]  "EN954 Safety Category 1"
$opt.d[20]  "EN954 Safety Category 3"
$opt.d[21]  "Alternate Servo Allocation"
$opt.d[22]  "FlexFeeder #1"
$opt.d[23]  "FlexFeeder #2"
$opt.d[24]  "AdeptWindows"
$opt.d[25]  "EVI Vision"
$opt.d[26]  "AIM Versions 3.1, 3.2, 3.3"
$opt.d[27]  "V+ Version 12"
$opt.d[28]  "V+ Version 13"
$opt.d[29]  "Digital Workcell Simulation Mode"
$opt.d[30]  "V+ Version 14"
$opt.d[31]  "HPS Application"
$opt.d[32]  "Adept iSight"
$opt.d[33]  "AIM Version 4"
$opt.d[34]  "V+ Version 15"
$opt.d[35]  "AIM NanoWare"
$opt.d[36]  "AIM LabView Interface"
$opt.d[37]  "AIM LaserWeld Interface"
$opt.d[38]  "ActiveV+ Software"
$opt.d[39]  "Continuous-Turn Joint 6"
$opt.d[40]  "V+ Version 16"
$opt.d[41]  "Adept Certified Developer App."
$opt.d[42]  "PLC Server Application"
$opt.d[43]  "Adept DeskTop Version 4"
$opt.d[44]  "Adept ACE Motion"
$opt.d[45]  "V+ Version 17"
$opt.d[46]  "TCP/IP Server Application"
$opt.d[47]  "Force Jog"
$opt.d[48]  "Three Adept Robots"
$opt.dipsw.lbl[1,0] "User interface via serial port"
$opt.dipsw.lbl[1,1] "User interface via serial port"
$opt.dipsw.lbl[1,2] "User interface via serial AdeptWindows"
$opt.dipsw.lbl[1,3] "User interface via Ethernet AdeptWindows (use stored IP
 address)"
$opt.dipsw.lbl[1,4] "User interface via Ethernet AdeptWindows (use default I
P address)"
$opt.dipsw.lbl[2,0] "DDT/V+ Monitor on selected user interface"
$opt.dipsw.lbl[2,1] "DDT/V+ Monitor on serial line"
$opt.dipsw.lbl[3,0] "Disable V+ auto-start"
$opt.dipsw.lbl[3,1] "Enable V+ auto-start"
$opt.dipsw.lbl[4,0] "Enable auto-boot"
$opt.dipsw.lbl[4,1] "Disable auto-boot"
$opt.ip.def.addr "172.16.125.127|255.255.0.0|172.16.200.1"
$opt.ip.default "0.0.0.0|0.0.0.0"
$opt.key    "ENTER"
$opt.model[1] "Adept MV-8"
$opt.model[2] "Adept MV-19"
$opt.model[3] "Adept MV-8"
$opt.model[4] "Adept MV-19"
$opt.model[5] "Adept MV-5 controller"
$opt.model[6] "Adept MV-10 controller"
$opt.model[7] "Adept MV-5 robot controller"
$opt.model[8] "Adept MV-10 robot controller"
$opt.model[9] "Adept MV-4 controller"
$opt.model[10] "Adept SmartController CS"
$opt.model[11] "Adept SmartController CX"
$opt.model[12] "Adept SmartController CS"
$opt.model[13] "Adept SmartController CX"
$opt.model[14] "Adept SmartController CX with AdeptVision sAVI"
$opt.model[15] "Adept Cobra i600"
$opt.model[16] "Adept Cobra i800"
$opt.model[17] "Adept Cobra i800 IP65"
$opt.model[18] "Adept Cobra e-Vario 600"
$opt.model[19] "Adept Cobra e-Vario 800"
$opt.model[20] "Adept Cobra i800 Inverted"
$par2_s[1]  "cmd70"
$par2_s[2]  "0^j^m"
$par2_s[3]  "-295.17"
$par2_s[4]  "156.18"
$par2_s[5]  "462.18"
$par2_s[6]  "-241.92"
$par2_s[7]  "-89.66"
$par2_s[8]  "0^j^m"
$par2_s[9]  "0^j^m"
$par_s[1]   "cmd70"
$par_s[2]   "0"
$par_s[3]   "0"
$par_s[4]   "0^j^m"
$par_s[5]   "435.53"
$par_s[6]   "-85.61"
$par_s[7]   "318.70"
$par_s[8]   "1^j^m"
$res_str    "cmd15"
$return_val "1"
$sp.clr     "^{[H^{[J"
$sp.cursor.off "^{[?25l"
$sp.cursor.on "^{[?25h"
$sp.disks   "D"
$sp.hdr     "^{[H^{[J^m^j"
$sp.header[1] ".HEADER Robot Specification Data                             
Version 1.4"
$sp.header[2] ".HEADER Joint-Independent Specification Data                 
Version 1.4"
$sp.header[3] ".HEADER Joint Specification Data                             
Version 1.4"
$sp.header[4] ".HEADER SmartModules Robot Configuration Data File Version 2.
0"
$sp.header[5] ".HEADER SmartModules Axis Configuration Data File Version 2.0
"
$sp.header[6] ".HEADER Robot Specification Data                             
Version 1.3"
$sp.header[7] ".HEADER Joint-Independent Specification Data                 
Version 1.3"
$sp.header[8] ".HEADER Joint Specification Data                             
Version 1.3"
$sp.key     "ENTER"
$sp.nulls   "^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`"
$sp.spaces  "                                                               
                                                                 "
$sp.tab     "^i"
$sp.tabs    "^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i"
$sv.client_ip "172.16.200.100"
$sv.data[1,0] "^`^`?^à^`^`ÿþ^`"
$sv.data[2,0] "^`^`A^`^`^`^`p@^|^`^`^`^`^`^`           1024 09-May-13 11:04:
52 SYSTEM.DSKBD^`^`PS           4608 02-Mar-13 00:31:38 ADEPTSYS.ADMB@^`^`  
        "
$sv.data[2,1] "   6144 08-Feb-15 16:04:42 ALLPROGS.V2BD^`^`PS        2826752
 08-Sep-14 04:36:52 ADEPTSYS.SYSB8^`^`PS            512 16-Sep-09 17:57"
$sv.data[2,2] ":36 DUMMY.TMPB(^`^`D               0 09-May-13 10:54:54 CALIB
B,^`^`D               0 09-May-13 10:54:54 SYSTEMB$^`^`D               0 "
$sv.data[2,3] "17-Jun-08 18:47:08 UTILB4^`^`D               0 17-Jun-08 18:4
7:14 SPECDATAB ^`^`D               0 17-Jun-08 18:49:40 AIMB(^`^`D       "
$sv.data[2,4] "        0 02-Feb-14 03:40:38 ADEPTB0^`^`             6144 27-
Jan-15 17:11:16 AUTO.V2B4^`^`           115712 26-Apr-15 23:11:06 ROBOT"
$sv.data[2,5] ".PGB4^`^`             8192 26-Apr-15 23:11:06 ROBOT.LCB@^`^` 
           22016 21-May-14 00:37:40 MAN_AUTO.V2B4^`^`           189952 26"
$sv.data[2,6] "-Apr-15 23:11:08 ROBOT.REB4^`^`            19456 26-Apr-15 23
:11:08 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG@"
$sv.data[2,7] "^`^`             2048 13-Jun-00 21:54:18 11160-2.SPCB@^`^`   
          1536 13-Jun-00 21:54:22 11180-1.SPCB@^`^`             2048 13-J"
$sv.data[2,8] "un-00 21:54:26 11180-2.SPCB@^`^`             1536 13-Jun-00 2
1:54:30 11200-1.SPCB@^`^`             2048 13-Jun-00 21:54:34 11200-2.S"
$sv.data[2,9] "PCB@^`^`             1536 13-Jun-00 21:54:38 14030-1.SPCB@^`^
`             1536 13-Jun-00 21:54:42 14040-1.SPCB@^`^`             1536 "
$sv.data[2,10] "13-Jun-00 21:54:46 14050-1.SPCB@^`^`             1536 13-Jun
-00 21:54:50 14060-1.SPCB@^`^`             1536 13-Jun-00 21:54:54 14080"
$sv.data[2,11] "-1.SPCB@^`^`             1536 13-Jun-00 21:54:58 14100-1.SPC
B@^`^`             1536 13-Jun-00 21:55:02 17120-1.SPCB@^`^`             2"
$sv.data[2,12] "048 13-Jun-00 21:55:06 17120-2.SPCB8^`^`             1536 13
-Jun-00 21:55:10 20025.SPCB8^`^`             1536 13-Jun-00 21:55:16 200"
$sv.data[2,13] "35.SPCB8^`^`             1536 13-Jun-00 21:55:20 20045.SPCB8
^`^`             1536 13-Jun-00 21:55:24 20055.SPCB8^`^`             1536 "
$sv.data[2,14] "13-Jun-00 21:55:30 20075.SPCB8^`^`             1536 13-Jun-0
0 21:55:34 20095.SPCB8^`^`             1536 13-Jun-00 21:55:40 21115.SPC"
$sv.data[2,15] "B8^`^`             1536 13-Jun-00 21:55:44 21135.SPCB8^`^`  
           1536 13-Jun-00 21:55:50 21155.SPCB8^`^`             1536 13-Jun"
$sv.data[2,16] "-00 21:55:54 24025.SPCB8^`^`             1536 13-Jun-00 21:5
5:58 24035.SPCB8^`^`             1536 13-Jun-00 21:56:04 24045.SPCB8^`^`  "
$sv.data[2,17] "           1536 13-Jun-00 21:56:08 24055.SPCB8^`^`          
   1536 13-Jun-00 21:56:14 24075.SPCB8^`^`             1536 13-Jun-00 21"
$sv.data[2,18] ":56:18 24095.SPCB8^`^`             1536 13-Jun-00 21:56:22 3
0013.SPCB8^`^`             1536 13-Jun-00 21:56:28 30023.SPCB8^`^`        "
$sv.data[2,19] "     1536 13-Jun-00 21:56:34 30033.SPCB8^`^`             153
6 13-Jun-00 21:56:40 30043.SPCB8^`^`             1536 13-Jun-00 21:56:46"
$sv.data[2,20] " 30053.SPCB8^`^`             1536 13-Jun-00 21:56:52 31063.S
PCB8^`^`             1536 13-Jun-00 21:56:58 40013.SPCB8^`^`             1"
$sv.data[2,21] "536 13-Jun-00 21:57:04 40023.SPCB8^`^`             1536 13-J
un-00 21:57:08 41033.SPCB8^`^`             1536 13-Jun-00 21:57:14 41043"
$sv.data[2,22] ".SPCB8^`^`             1536 13-Jun-00 21:57:20 41053.SPCB8^`
^`             1536 13-Jun-00 21:57:26 41063.SPCB8^`^`             1536 13"
$sv.data[2,23] "-Jun-00 21:57:32 45043.SPCB8^`^`             2048 13-Jun-00 
21:57:38 50000.SPCB8^`^`             2048 13-Jun-00 21:57:44 51000.SPCB8"
$sv.data[2,24] "^`^`             2048 13-Jun-00 21:57:48 52000.SPCB8^`^`    
         1024 13-Jun-00 21:52:50 ELM_X.SPCB<^`^`             1024 13-Jun-0"
$sv.data[2,25] "0 21:52:54 ELM_XY.SPCB@^`^`             1536 13-Jun-00 21:52
:56 ELM_XYZ.SPCBD^`^`             1536 13-Jun-00 21:53:00 ELM_XYZT.SPCB<"
$sv.data[2,26] "^`^`             1024 13-Jun-00 21:53:02 ELM_XZ.SPCB8^`^`   
          1024 13-Jun-00 21:53:06 ELM_Y.SPCB@^`^`             1536 13-Jun-"
$sv.data[2,27] "00 21:53:08 ELM_YZT.SPCB8^`^`             1024 13-Jun-00 21:
53:12 ELM_Z.SPCB4^`^`             1024 13-Jun-00 21:52:26 LM_X.SPCB8^`^`  "
$sv.data[2,28] "           1024 13-Jun-00 21:52:30 LM_XY.SPCB<^`^`          
   1536 13-Jun-00 21:52:32 LM_XYZ.SPCB@^`^`             1536 13-Jun-00 2"
$sv.data[2,29] "1:52:36 LM_XYZT.SPCB8^`^`             1024 13-Jun-00 21:52:3
8 LM_XZ.SPCB4^`^`             1024 13-Jun-00 21:52:42 LM_Y.SPCB<^`^`      "
$sv.data[2,30] "       1536 13-Jun-00 21:52:44 LM_YZT.SPCB4^`^`             
1024 13-Jun-00 21:52:48 LM_Z.SPCB@^`^`             4096 26-Apr-10 23:00:"
$sv.data[2,31] "10 MB10_10.SPCB@^`^`             4608 26-Apr-10 23:00:10 MB1
0_12.SPCB@^`^`             5120 26-Apr-10 23:00:10 MB10_20.SPCB@^`^`      "
$sv.data[2,32] "       5632 26-Apr-10 23:00:10 MB10_22.SPCB@^`^`            
 3072 26-Apr-10 23:00:10 MB10_40.SPCB@^`^`             3072 26-Apr-10 23"
$sv.data[2,33] ":00:10 MB10_42.SPCB@^`^`             3584 26-Apr-10 23:00:10
 MB10_45.SPCB@^`^`             3584 26-Apr-10 23:00:10 MB10_47.SPCB@^`^`  "
$sv.data[2,34] "           4096 26-Apr-10 23:00:10 MB10_60.SPCB@^`^`        
     4608 26-Apr-10 23:00:10 MB10_70.SPCB@^`^`             4608 26-Apr-1"
$sv.data[2,35] "0 23:00:10 MB10_91.SPCB@^`^`             5120 26-Apr-10 23:0
0:10 MB10_92.SPCBD^`^`             5632 26-Apr-10 23:00:10 MBYG1100.SPCB"
$sv.data[2,36] "D^`^`             6144 26-Apr-10 23:00:10 MBYG1200.SPCBD^`^`
             6144 26-Apr-10 23:00:10 MBYG1400.SPCBD^`^`             6144 2"
$sv.data[2,37] "6-Apr-10 23:00:10 MBYG1750.SPCBD^`^`             5632 26-Apr
-10 23:00:10 MBYG2100.SPCBD^`^`             5632 26-Apr-10 23:00:10 MBYG"
$sv.data[2,38] "2200.SPCBD^`^`             5632 26-Apr-10 23:00:10 MBYG2400.
SPCBD^`^`             5632 26-Apr-10 23:00:10 MBYG2750.SPCB@^`^`          "
$sv.data[2,39] "  33792 26-Apr-10 23:00:10 MB_PYTH.SPCB@^`^`             102
4 26-Apr-10 23:00:10 QP08360.SPCB@^`^`             1024 26-Apr-10 23:00:"
$sv.data[2,40] "10 QP08660.SPCB@^`^`             1024 26-Apr-10 23:00:10 QP0
9023.SPCB@^`^`             1024 26-Apr-10 23:00:10 QP09068.SPCB@^`^`      "
$sv.data[2,41] "       1024 26-Apr-10 23:00:10 QP09503.SPCB@^`^`            
 1024 26-Apr-10 23:00:10 QP09730.SPCB@^`^`             1024 26-Apr-10 23"
$sv.data[2,42] ":00:10 QP09732.SPCB@^`^`             1024 26-Apr-10 23:00:10
 QP09734.SPCB@^`^`             4096 26-Apr-10 23:00:10 ROB_CFG.SPCB8^`^`  "
$sv.data[2,43] "           4096 26-Apr-10 23:00:10 SM_10.SPCB8^`^`          
   4608 26-Apr-10 23:00:10 SM_20.SPCB8^`^`             3072 26-Apr-10 23"
$sv.data[2,44] ":00:10 SM_40.SPCB8^`^`             3584 26-Apr-10 23:00:10 S
M_45.SPCB8^`^`             2560 26-Apr-10 23:00:10 SM_50.SPCB8^`^`        "
$sv.data[2,45] "     4096 26-Apr-10 23:00:10 SM_60.SPCB8^`^`             409
6 26-Apr-10 23:00:10 SM_70.SPCB8^`^`             3584 26-Apr-10 23:00:10"
$sv.data[2,46] " SM_80.SPCB8^`^`             4608 26-Apr-10 23:00:10 SM_91.S
PCB@^`^`             5632 26-Apr-10 23:00:10 YSG1100.SPCB@^`^`            "
$sv.data[2,47] " 5632 26-Apr-10 23:00:10 YSG1200.SPCB@^`^`             5632 
26-Apr-10 23:00:10 YSG1400.SPCB@^`^`             5632 26-Apr-10 23:00:10"
$sv.data[2,48] " YSG1750.SPCB@^`^`            11776 27-Apr-10 19:59:20 _READ
ME.TXTBD^`^`             1024 26-Apr-10 23:00:10 QP09503L.SPCBD^`^`       "
$sv.data[2,49] "      1024 26-Apr-10 23:00:10 QP09730L.SPCBD^`^`            
 1024 26-Apr-10 23:00:10 QP09732L.SPCBD^`^`             1024 26-Apr-10 2"
$sv.data[2,50] "3:00:10 QP09734L.SPC"
$sv.data[3,0] "^`^`A^`^`^`^`q@È^à^`^`^`^`^`p^`^`SWITCH(DRY.RUN)^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ^`Íÿè^`^`^`^`^`@^`^`^`?^à^`^`
^`^`^`^`^`^`^`^`?^à^`^`@@^`^`?^à^`^`Íÿè^`^`^`^`^`@^`^`^`?^à^`^`^`^`^`"
$sv.data[3,1] "^`^`^`^`^`?^à^`^`@^à^`^`?^à^`^`Íÿè^`^`^`^`^`@^`^`^`?^à^`^`^`^
`^`^`^`^`^`^`@^`^`^`@^à^`^`?^à^`^`Íÿè^`^`^`^`^`@à^`^`?^à^`^`^`^`^`^`^`^`^`^`
?^à^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`@^à^`^`?^à^`^`^`^`^`^`^`^`^`^`?^à^`^`
^`^`^`^`^`^`^`^`^`^`^`"
$sv.data[3,2] "^`^`^`^`^`@^à^`^`?^à^`^`^`^`^`^`^`^`^`^`@@^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`@@^`^`?^à^`^`^`^`^`^`^`^`^`^`?^à^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`@@^`^`?^à^`^`^`^`^`^`^`^`^`^`@@^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`
             0 "
$sv.data[3,3] "17-Jun-08 18:47:08 UTILB4^`^`D               0 17-Jun-08 18:4
7:14 SPECDATAB ^`^`D               0 17-Jun-08 18:49:40 AIMB(^`^`D       "
$sv.data[3,4] "        0 02-Feb-14 03:40:38 ADEPTB0^`^`             6144 27-
Jan-15 17:11:16 AUTO.V2B4^`^`           114688 09-Mar-15 07:28:22 ROBOT"
$sv.data[3,5] ".PGB4^`^`             8192 09-Mar-15 07:28:22 ROBOT.LCB@^`^` 
           22016 21-May-14 00:37:40 MAN_AUTO.V2B4^`^`           189952 09"
$sv.data[3,6] "-Mar-15 07:28:24 ROBOT.REB4^`^`            18944 09-Mar-15 07
:28:26 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG "
$sv.data[3,7] "            8704 15-Feb-96 20:09:16 LOADICON.V2B<^`^`        
     6656 15-Nov-01 22:14:46 LOADTCH.V2B@^`^`            21504 23-May-0"
$sv.data[3,8] "5 23:48:20 PROFILER.V2B@^`^`            67072 09-May-13 15:25
:12 RSC_RSTR.V2B@^`^`           124416 30-Apr-13 23:20:52 SAFE_UTL.V2B8"
$sv.data[3,9] "^`^`            22016 27-Aug-02 23:22:32 SFUTIL.V2BD^`^`     
        9728 24-Jan-08 21:34:44 SMARTLNK.LIBB8^`^`            19968 09-Se"
$sv.data[3,10] "p-09 23:56:38 SM_CAL.V2B0^`^`           229376 19-Feb-10 00:
13:30 SPEC.V2B@^`^`            50176 14-Apr-11 23:11:10 SPECSUB.LIBB<^`^` "
$sv.data[3,11] "            5632 18-May-01 19:50:16 SQUEEZE.V2B@^`^`        
    22016 19-Feb-10 00:13:38 SRVUTIL.LIBB@^`^`             9728 28-Jul-0"
$sv.data[3,12] "0 03:09:30 TOUCHCAL.V2B@^`^`             6656 25-Oct-02 03:0
1:36 VPROTECT.V2B8^`^`            23552 27-Aug-02 20:43:22 XMODEM.V2B<^`^`"
$sv.data[3,13] "            23552 27-Aug-02 20:43:22 ZZMODEM.V2B@^`^`       
      5632 09-May-13 15:42:06 _README.TXT"
$sv.data[4,0] "^`^`?^à^`^`ÿû^`^a@Z@^`^`^`^`^`^a^a^a^aTCH(ROBOT[1])^`^`^`^`^`
^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^à^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`      4608 0
2-Mar-13 00:31:38 ADEPTSYS.ADMB@^`^`          "
$sv.data[4,1] "   6144 08-Feb-15 16:04:42 ALLPROGS.V2BD^`^`PS        2826752
 08-Sep-14 04:36:52 ADEPTSYS.SYSB8^`^`PS            512 16-Sep-09 17:57"
$sv.data[4,2] ":36 DUMMY.TMPB(^`^`D               0 09-May-13 10:54:54 CALIB
B,^`^`D               0 09-May-13 10:54:54 SYSTEMB$^`^`D               0 "
$sv.data[4,3] "17-Jun-08 18:47:08 UTILB4^`^`D               0 17-Jun-08 18:4
7:14 SPECDATAB ^`^`D               0 17-Jun-08 18:49:40 AIMB(^`^`D       "
$sv.data[4,4] "        0 02-Feb-14 03:40:38 ADEPTB0^`^`             6144 27-
Jan-15 17:11:16 AUTO.V2B4^`^`           113664 08-Feb-15 16:03:32 ROBOT"
$sv.data[4,5] ".PGB4^`^`             8192 04-Mar-15 17:18:02 ROBOT.LCB@^`^` 
           22016 21-May-14 00:37:40 MAN_AUTO.V2B4^`^`            32768 04"
$sv.data[4,6] "-Mar-15 17:18:04 ROBOT.REB4^`^`            11264 04-Mar-15 17
:18:04 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG"
$sv.data[5,0] "^`^`A^`^`^`^`o^`^`^`^`^`^`^`^`p^`^`SWITCH(DRY.RUN)to this pro
gram*^`^`^`^`B^è^`^`25;sv.q_mgr,10;sv.handle,10;sv.set_tool,5;sv.reacte,8;sv
.set_err,19;^`^`"
$sv.data[5,1] "^`^`^m^jAdept CoC^`^`^`bra s350/s600/s800 Robot Module.^m^jAd
ept Cobra s350/s600/s800 Robot Module #2.^m^j^m^jSoftware:    17.2 7-3100  (
Edit"
$sv.data[5,2] " C2, 13-Feb-2013C^`^`^`, Production Release)^m^jController:  
2000-48470 108 0 ^m^jSecurity ID: D751-8CFB-470A^m^jProcessor 1: 0.52 7-5 32
"
$sv.data[5,3] "MB^m^jRobot 1:     578C^`^`^`-253 0-241-1 6 ^m^j             
Adept Cobra s350/s600/s800 Robot Module.^m^jRobot 2:     578-252 0-241-1 6 ^
m"
$sv.data[5,4] "^j             Adept CobrB´^`^`a s350/s600/s800 Robot Module 
#2.^m^jServo:       16.0 (Edit A1)^m^j^m^j21-Apr-2015 00:09:25^m^j^m^j^`^`^`
^`^`^`^`^`^`^`"
$sv.data[5,5] "^`^`GB4^`^`             8192 05-Apr-15 23:36:22 ROBOT.LCB@^`^
`            22016 21-May-14 00:37:40 MAN_AUTO.V2B4^`^`           189952 05"
$sv.data[5,6] "-Apr-15 23:36:24 ROBOT.REB4^`^`            18944 05-Apr-15 23
:36:24 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG"
$sv.error[0] ""
$sv.error[1] ""
$sv.error[2] ""
$sv.error[3] ""
$sv.error[4] ""
$sv.error[5] ""
$sv.error[6] ""
$sv.error[7] ""
$sv.error[8] ""
$sv.error[9] ""
$sv.error[10] ""
$sv.error[11] ""
$sv.error[12] ""
$sv.error[13] ""
$sv.error[14] ""
$sv.error[15] ""
$sv.error[16] ""
$sv.error[17] ""
$sv.error[18] ""
$sv.error[19] ""
$sv.error[20] ""
$sv.error[21] ""
$sv.error[22] ""
$sv.error[23] ""
$sv.error[24] ""
$sv.error[25] ""
$sv.error[26] ""
$sv.error[27] ""
$sv.hash    "479cf22666ef325584b7e9beb903918c"
$sv.stack[24,0] ""
$sv.stack[24,1] ""
$sv.stack[25,0] ""
$sv.stack[25,1] ""
$sv.stack[26,0] ""
$sv.stack[26,1] ""
$sv.stack[27,0] ""
$sv.stack[27,1] ""
$sv.version "$Revision: 27967 $"
$sv.vplus_edit "C2"
.END

