.STRINGS
$ca.err[1]  ""
$ca.err[2]  ""
$ca.err[3]  ""
$ca.err[4]  ""
$ca.reg.mod[1] "a.scobra.cal"
$cf.clr     "^^{[H^^{[J"
$cf.dev     "DISK>"
$cf.dir     "\CONFIG_C\"
$cf.file    "ADEPTSYS.CFG"
$cf.key     "ENTER"
$cmd_str[1,1] "99"
$cmd_str[1,2] "15"
$cmd_str[2,1] "99"
$cmd_str[2,2] "15"
$cmd_str2   "15"
$come_str[1,1] ""
$come_str[1,2] ""
$come_str[2,1] ""
$come_str[2,2] ""
$come_str[1] "cmd70,0,0^^^^^^^^^^^^^^^^j^^^^^^^^^^^^^^^^m"
$come_str[2] "^^^^^^^^^^^^^^^^`"
$err_code[1] "1"
$err_code[2] "1"
$err_message[1] " -406"
$err_message[2] " -406"
$fw.gtype[0] "Empty"
$fw.gtype[1] "Node information"
$fw.gtype[2] "Axis"
$fw.gtype[3] "Digital input"
$fw.gtype[4] "Digital output"
$fw.gtype[5] "Serial I/O"
$fw.gtype[6] "Fast digital input"
$fw.gtype[7] "Multi-axis robot"
$fw.module  "SMARTLNK"
$fw.version "16.4A2"
$opt.d[1]   "V+ Version 11"
$opt.d[2]   "V+ Extensions"
$opt.d[3]   "OEM Option"
$opt.d[4]   "Kinematic Modules"
$opt.d[5]   "Integrated Motion and Vision"
$opt.d[6]   "Vision"
$opt.d[7]   "Enhanced Kinematic Modules"
$opt.d[8]   "AIM Versions 2.3 and 3.0"
$opt.d[9]   "AIM Extensions"
$opt.d[10]  "Adept Robot"
$opt.d[11]  "GEM and SECS-I/II Applications"
$opt.d[12]  "AIM Applications"
$opt.d[13]  "Enhanced Trajectory Control"
$opt.d[14]  "AdeptTCP/IP Protocol Access"
$opt.d[15]  "AdeptNFS Client"
$opt.d[16]  "AdeptFTP Client/Server"
$opt.d[17]  "Two Adept Robots"
$opt.d[18]  "Third-Party Board Support"
$opt.d[19]  "EN954 Safety Category 1"
$opt.d[20]  "EN954 Safety Category 3"
$opt.d[21]  "Alternate Servo Allocation"
$opt.d[22]  "FlexFeeder #1"
$opt.d[23]  "FlexFeeder #2"
$opt.d[24]  "AdeptWindows"
$opt.d[25]  "EVI Vision"
$opt.d[26]  "AIM Versions 3.1, 3.2, 3.3"
$opt.d[27]  "V+ Version 12"
$opt.d[28]  "V+ Version 13"
$opt.d[29]  "Digital Workcell Simulation Mode"
$opt.d[30]  "V+ Version 14"
$opt.d[31]  "HPS Application"
$opt.d[32]  "Adept iSight"
$opt.d[33]  "AIM Version 4"
$opt.d[34]  "V+ Version 15"
$opt.d[35]  "AIM NanoWare"
$opt.d[36]  "AIM LabView Interface"
$opt.d[37]  "AIM LaserWeld Interface"
$opt.d[38]  "ActiveV+ Software"
$opt.d[39]  "Continuous-Turn Joint 6"
$opt.d[40]  "V+ Version 16"
$opt.d[41]  "Adept Certified Developer App."
$opt.d[42]  "PLC Server Application"
$opt.d[43]  "Adept DeskTop Version 4"
$opt.d[44]  "Adept ACE Motion"
$opt.d[45]  "V+ Version 17"
$opt.d[46]  "TCP/IP Server Application"
$opt.d[47]  "Force Jog"
$opt.d[48]  "Three Adept Robots"
$opt.dipsw.lbl[1,0] "User interface via serial port"
$opt.dipsw.lbl[1,1] "User interface via serial port"
$opt.dipsw.lbl[1,2] "User interface via serial AdeptWindows"
$opt.dipsw.lbl[1,3] "User interface via Ethernet AdeptWindows (use stored IP
 address)"
$opt.dipsw.lbl[1,4] "User interface via Ethernet AdeptWindows (use default I
P address)"
$opt.dipsw.lbl[2,0] "DDT/V+ Monitor on selected user interface"
$opt.dipsw.lbl[2,1] "DDT/V+ Monitor on serial line"
$opt.dipsw.lbl[3,0] "Disable V+ auto-start"
$opt.dipsw.lbl[3,1] "Enable V+ auto-start"
$opt.dipsw.lbl[4,0] "Enable auto-boot"
$opt.dipsw.lbl[4,1] "Disable auto-boot"
$opt.ip.def.addr "172.16.125.127|255.255.0.0|172.16.200.1"
$opt.ip.default "0.0.0.0|0.0.0.0"
$opt.key    "ENTER"
$opt.model[1] "Adept MV-8"
$opt.model[2] "Adept MV-19"
$opt.model[3] "Adept MV-8"
$opt.model[4] "Adept MV-19"
$opt.model[5] "Adept MV-5 controller"
$opt.model[6] "Adept MV-10 controller"
$opt.model[7] "Adept MV-5 robot controller"
$opt.model[8] "Adept MV-10 robot controller"
$opt.model[9] "Adept MV-4 controller"
$opt.model[10] "Adept SmartController CS"
$opt.model[11] "Adept SmartController CX"
$opt.model[12] "Adept SmartController CS"
$opt.model[13] "Adept SmartController CX"
$opt.model[14] "Adept SmartController CX with AdeptVision sAVI"
$opt.model[15] "Adept Cobra i600"
$opt.model[16] "Adept Cobra i800"
$opt.model[17] "Adept Cobra i800 IP65"
$opt.model[18] "Adept Cobra e-Vario 600"
$opt.model[19] "Adept Cobra e-Vario 800"
$opt.model[20] "Adept Cobra i800 Inverted"
$par2_s[1]  "cmd99"
$par2_s[2]  "0^j^m"
$par2_s[3]  "-292.04"
$par2_s[4]  "17.53"
$par2_s[5]  "369.35"
$par2_s[6]  "-224.71"
$par2_s[7]  "-44.88"
$par2_s[8]  "0^j^m"
$par2_s[9]  "0^^j^^m"
$par_s[1]   "cmd99"
$par_s[2]   "0^j^m"
$par_s[3]   "0"
$par_s[4]   "0^j^m"
$par_s[5]   "463.68"
$par_s[6]   "-78.22"
$par_s[7]   "7.85"
$par_s[8]   "1^j^m"
$res_str    "cmd15"
$return_val "1"
$sp.clr     "^{[H^{[J"
$sp.cursor.off "^{[?25l"
$sp.cursor.on "^{[?25h"
$sp.disks   "D"
$sp.hdr     "^{[H^{[J^m^j"
$sp.header[1] ".HEADER Robot Specification Data                             
Version 1.4"
$sp.header[2] ".HEADER Joint-Independent Specification Data                 
Version 1.4"
$sp.header[3] ".HEADER Joint Specification Data                             
Version 1.4"
$sp.header[4] ".HEADER SmartModules Robot Configuration Data File Version 2.
0"
$sp.header[5] ".HEADER SmartModules Axis Configuration Data File Version 2.0
"
$sp.header[6] ".HEADER Robot Specification Data                             
Version 1.3"
$sp.header[7] ".HEADER Joint-Independent Specification Data                 
Version 1.3"
$sp.header[8] ".HEADER Joint Specification Data                             
Version 1.3"
$sp.key     "ENTER"
$sp.nulls   "^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`"
$sp.spaces  "                                                               
                                                                 "
$sp.tab     "^i"
$sp.tabs    "^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^
i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i^i"
$sv.client_ip "172.16.200.100"
$sv.data[1,0] "^`^`?^à^`^`ÿþ^`"
$sv.data[2,0] "^`^`@^`^`^`^~^g^`ded^a^`d^`           4608 02-Mar-13 00:31:40
 ADEPTSYS.ADMB@^`^`             6144 09-Nov-14 00:44:54 ALLPROGS.V2BD^`^`PS 
      "
$sv.data[2,1] " 2685440 26-Aug-14 08:10:14 ADEPTSYS.SYSB(^`^`D              
 0 30-Nov-13 22:56:28 ADEPTB<^`^`             1024 30-Nov-13 23:03:44 S"
$sv.data[2,2] "YSTEM.DSKB(^`^`D               0 30-Nov-13 23:03:44 CALIBB,^`
^`D               0 30-Nov-13 23:03:46 SYSTEMB$^`^`D               0 30-N"
$sv.data[2,3] "ov-13 23:05:00 UTILBD^`^`PS           9216 27-Aug-14 01:10:18
 ADEPTSYS.CFGB4^`^`D               0 06-Dec-13 08:09:50 SPECDATAB0^`^`   "
$sv.data[2,4] "          6144 09-Nov-14 00:44:54 AUTO.V2B4^`^`           113
664 14-Jan-15 01:18:52 ROBOT.PGB4^`^`             8192 02-Feb-15 05:36:"
$sv.data[2,5] "16 ROBOT.LCB4^`^`           189952 02-Feb-15 05:36:24 ROBOT.R
EB4^`^`            11776 02-Feb-15 05:36:24 ROBOT.ST          189440 09"
$sv.data[2,6] "-Sep-14 03:53:58 ROBOT.REB4^`^`             7168 09-Sep-14 03
:54:00 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG"
$sv.data[3,0] "^`^`@^`^`^`ÿü^`d^à^`^`^`^`^`p^`^`SWITCH(DRY.RUN)^`^`^`^`^`^`^
`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ        6144 09-Nov-14 00:44:
54 ALLPROGS.V2BD^`^`PS       "
$sv.data[3,1] " 2685440 26-Aug-14 08:10:14 ADEPTSYS.SYSB(^`^`D              
 0 30-Nov-13 22:56:28 ADEPTB<^`^`             1024 30-Nov-13 23:03:44 S"
$sv.data[3,2] "YSTEM.DSKB(^`^`D               0 30-Nov-13 23:03:44 CALIBB,^`
^`D               0 30-Nov-13 23:03:46 SYSTEMB$^`^`D               0 30-N"
$sv.data[3,3] "ov-13 23:05:00 UTILBD^`^`PS           9216 27-Aug-14 01:10:18
 ADEPTSYS.CFGB4^`^`D               0 06-Dec-13 08:09:50 SPECDATAB0^`^`   "
$sv.data[3,4] "          6144 09-Nov-14 00:44:54 AUTO.V2B4^`^`           113
664 14-Jan-15 01:18:52 ROBOT.PGB4^`^`             8192 14-Jan-15 01:18:"
$sv.data[3,5] "52 ROBOT.LCB4^`^`           189952 14-Jan-15 01:18:54 ROBOT.R
EB4^`^`            11776 14-Jan-15 01:18:54 ROBOT.ST          189440 20"
$sv.data[3,6] "-Oct-14 08:04:34 ROBOT.REB4^`^`             8192 20-Oct-14 08
:04:34 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG"
$sv.data[4,0] "^`^`?^à^`^`ÿû^`^`^`^`^`^`^`^`p^`^`SWITCH(DRY.RUN)^`^`^`^`^`^`
^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`^`        6144
 09-Nov-14 00:44:54 ALLPROGS.V2BD^`^`PS       "
$sv.data[4,1] " 2685440 26-Aug-14 08:10:14 ADEPTSYS.SYSB(^`^`D              
 0 30-Nov-13 22:56:28 ADEPTB<^`^`             1024 30-Nov-13 23:03:44 S"
$sv.data[4,2] "YSTEM.DSKB(^`^`D               0 30-Nov-13 23:03:44 CALIBB,^`
^`D               0 30-Nov-13 23:03:46 SYSTEMB$^`^`D               0 30-N"
$sv.data[4,3] "ov-13 23:05:00 UTILBD^`^`PS           9216 27-Aug-14 01:10:18
 ADEPTSYS.CFGB4^`^`D               0 06-Dec-13 08:09:50 SPECDATAB0^`^`   "
$sv.data[4,4] "          6144 09-Nov-14 00:44:54 AUTO.V2B4^`^`           111
104 14-Nov-14 00:39:08 ROBOT.PGB4^`^`             8192 15-Nov-14 23:32:"
$sv.data[4,5] "40 ROBOT.LCB4^`^`           189440 15-Nov-14 23:32:42 ROBOT.R
EB4^`^`             8704 15-Nov-14 23:32:42 ROBOT.ST          189440 05"
$sv.data[4,6] "-Nov-14 05:30:28 ROBOT.REB4^`^`             8192 05-Nov-14 05
:30:28 ROBOT.STBD^`^`PS           5120 08-Sep-14 03:52:14 ADEPTSYS.CFG"
$sv.data[5,0] "^`^`@^`^`^`^~^c^`^ted^a^`^t^`p^`^`SWITCH(DRY.RUN)to this prog
ram*^`^`^`^`B^è^`^`25;sv.q_mgr,10;sv.handle,10;sv.set_tool,5;sv.reacte,8;sv.
set_err,19;^`^`"
$sv.data[5,1] "^`^`^m^jAdept CoC^`^`^`bra s350/s600/s800 Robot Module.^m^jAd
ept Cobra s350/s600/s800 Robot Module #2.^m^j^m^jSoftware:    17.2 7-3100  (
Edit"
$sv.data[5,2] " C2, 13-Feb-2013C^`^`^`, Production Release)^m^jController:  
2000-40551 108 0 ^m^jSecurity ID: DC62-9249-7EAA^m^jProcessor 1: 0.52 7-5 32
"
$sv.data[5,3] "MB^m^jRobot 1:     578C^`^`^`-361 0-241-1 6 ^m^j             
Adept Cobra s350/s600/s800 Robot Module.^m^jRobot 2:     578-362 0-241-1 6 ^
m"
$sv.data[5,4] "^j             Adept CobrBÖ^`^`a s350/s600/s800 Robot Module 
#2.^m^jServo:       16.0 (Edit A1)^m^j^m^j12-Feb-2015 19:40:17^m^j^m^jAuto S
tart"
$sv.data[5,5] "up...^m^j^`^`^`^`^`^`^`^`^`^`^`^`       189952 25-Dec-14 04:3
0:40 ROBOT.REB4^`^`            11776 25-Dec-14 04:30:40 ROBOT.ST"
$sv.error[0] ""
$sv.error[1] ""
$sv.error[2] ""
$sv.error[3] ""
$sv.error[4] ""
$sv.error[5] ""
$sv.error[6] ""
$sv.error[7] ""
$sv.error[8] ""
$sv.error[9] ""
$sv.error[10] ""
$sv.error[11] ""
$sv.error[12] ""
$sv.error[13] ""
$sv.error[14] ""
$sv.error[15] ""
$sv.error[16] ""
$sv.error[17] ""
$sv.error[18] ""
$sv.error[19] ""
$sv.error[20] ""
$sv.error[21] ""
$sv.error[22] ""
$sv.error[23] ""
$sv.error[24] ""
$sv.error[25] ""
$sv.error[26] ""
$sv.error[27] ""
$sv.hash    "479cf22666ef325584b7e9beb903918c"
$sv.pf.ip   "172.16.100.100"
$sv.stack[24,0] ""
$sv.stack[24,1] ""
$sv.stack[25,0] ""
$sv.stack[25,1] ""
$sv.stack[26,0] ""
$sv.stack[26,1] ""
$sv.stack[27,0] ""
$sv.stack[27,1] ""
$sv.version "$Revision: 27967 $"
$sv.vplus_edit "C2"
.END

